# Generated by Django 5.1.6 on 2025-07-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userbehavior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbehavior',
            old_name='clicked',
            new_name='added_to_cart',
        ),
        migrations.RemoveField(
            model_name='userbehavior',
            name='scrolled',
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home'), ('product', 'Product'), ('category', 'Category'), ('search', 'Search'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='scroll_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
