# Generated by Django 5.1.6 on 2025-07-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_clicked_userbehavior_added_to_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='device_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='page_type',
            field=models.CharField(max_length=100),
        ),
    ]
