# Generated by Django 5.1.6 on 2025-07-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_userbehavior_device_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBehavior',
        ),
    ]
